# (C) 2022 GoodData Corporation
# This file is used to produce GoodData Public Demo artifact for the usage in GoodData Anywhere / Tiger.
#
# Repository is registered on GitLab using the "CI/CD for external repo" so after the successful merge or PRs in Github,
# this pipeline definition is executed. It's not in any way blocking the existing delivery and deployment with internal CI / CD process.
#
# Delivery is managed by the CI / CD pipeline in gooddata/gdc-nas repository.
---
default:
  image: $AWS_ECR_URL/infra/tools:$BUILD_IMAGE_VERSION

variables:
  AWS_ECR_URL: '441851189095.dkr.ecr.eu-central-1.amazonaws.com'
  BUILD_IMAGE_VERSION: '3.5.0'

stages:
  - generate-update

### Job templates
.post-merge: &post-merge
  # trigger on push to master, release, hotfix/(tiger|panther) or fast_track branch
  if: '$CI_COMMIT_BRANCH =~ /^(master|release|hotfix\/(tiger|panther)|fast_track)$/
        && $CI_PIPELINE_SOURCE == "push"'

generate-update:
  stage: generate-update
  script:
    - /scripts/update_ext_image_version.py demo-resources
  dependencies: []
  rules:
    - <<: *post-merge
